### ISSUE TITLE
Blink doesn't render the form properly 

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/month-of-code#2]
On Blink : 
![Blink form render issue](https://cloud.githubusercontent.com/assets/3112509/25584723/ce8b5f3e-2eb4-11e7-9f2b-0e9e6f6a83a7.png)

Gecko :![Gecko no issue](https://cloud.githubusercontent.com/assets/6577624/25649148/9bc17e2a-2ff0-11e7-90a7-82a5b02cc1a4.png) 

### Any suggestions for how we can fix this?

**Comment by vinaypuppal** [comment]
Can you change color of <select/> or <option/> in css to black and see if text is visible? I am not able to reproduce it on my OSX chrome since chrome/browser uses O.S select box by default try above in your O.S and check if it works.

> On my chrome it looks okay
![screen shot 2017-05-03 at 12 25 30 pm](https://cloud.githubusercontent.com/assets/8843216/25650622/e2108744-2ffb-11e7-9acc-31772ae5b55f.png)

**Comment by vinaypuppal** [comment]
![screen shot 2017-05-03 at 12 25 30 pm](https://cloud.githubusercontent.com/assets/8843216/25650638/f6443026-2ffb-11e7-9598-afe8c97bd612.png)

Can you change color of `<select/>` or `<option/>` in css to `black` and see if text is visible? I am not able to reproduce it on my OSX chrome since browser uses O.S select box by default try above in your O.S and check if it works

**Comment by vramana** [comment]
Black seems to work 
![image](https://cloud.githubusercontent.com/assets/3112509/25673176/1352d03e-3054-11e7-9523-ea6880af4c80.png)
